# Site settings
title: The Cracked Bassoon
email: samuel.mathias@yale.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Sam Mathias, a researcheer at Yale University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sammosummo@github.io" # the base hostname & protocol for your site
twitter_username: crackedbassoon
github_username:  sammosummo

# Build settings
permalink: date
markdown: kramdown
