title: The Cracked Bassoon
email: sam@crackedbassoon.com
url: "https://crackedbassoon.com"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
highlighter: rouge
permalink: /writing/:title
redirects: yes
