# Site settings
email: samuel.mathias@yale.edu
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: The Cracked Bassoon
description: Website of Sam Mathias, a researcher at Yale
url: ""
twitter_username: crackedbassoon
default_img:

# Profile settings
name: Sam Mathias
profile_img: https://sammosummo.github.io/images/wedding_photo_2.jpg
profile: I'm a UK-born scientist at Yale. I'm interested in human perception and individual differences. I like to blog about genetics, psychophysics, and statistics.
social:
  id-card-o:
  github: https://github.com/sammosummo
  feed:

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt"]
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
