text_skin: default
highlight_theme: default
url: https://sammosummo.github.io
baseurl:  # unsure what this does
title: The Cracked Bassoon
description: >
  Personal website of Sam Mathias.
lang: en
timezone: America/New_York

author:
  type: person
  name: Samuel R. Mathias
  url: https://sammosummo.github.io
  avatar: https://www.gravatar.com/avatar/cf88687e01c21b5cd0fd0c7f5d5fe2c5
  bio: Researcher at Yale University
  email: samuel.mathias@gmail.com

repository: sammosummo/sammosummo.github.io
repository_tree: master

paths:
  root : # title link url, "/" (default)
  home : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss: # "/feed.xml" (default)

excerpt_separator: <!--more-->
excerpt_type: html

license: CC-BY-NC-4.0

toc:
  selectors: "h1,h2,h3"


mathjax: true
mathjax_autoNumber: true

mermaid: true

chart: true

paginate: 8
paginate_path: /page:num


sources: # bootcdn (default), unpkg


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji