# Site settings
email: samuel.mathias@yale.edu
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: The Cracked Bassoon
description: Website of Sam Mathias, a researcher at Yale
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Sam Mathias
profile_img: 
profile: I'm a UK-born scientist at Yale University. I'm interested in human perception, and the genetic and environmental factors underlying individual differences in perceptual abilities. Download my CV here, or view my publication list.
social:
  github: sammosummo

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
